apiVersion: v1
kind: Service
metadata:
  name: etl-app-service
  labels:
    app: etl-app
spec:
  selector:
    app: etl-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: ClusterIP
